name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build the Geode mod
      uses: geode-sdk/build-geode-mod@main
      with:
        bindings: geode-sdk/bindings
        sdk: nightly
        configure-args: '-DCMAKE_BUILD_TYPE=Release'
        build-config: Release
        path: geode-mod

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gd-mcp-mod-${{ matrix.config.name }}
        path: geode-mod/build/**/*.geode
